module.exports = {
  wikiSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'Comparisons',
      items: [{ type: 'autogenerated', dirName: 'comparisons' }],
    },
    {
      type: 'category',
      label: 'Entities',
      items: [{ type: 'autogenerated', dirName: 'entities' }],
    },
    {
      type: 'category',
      label: 'Presentations',
      items: [{ type: 'autogenerated', dirName: 'presentations' }],
    },
    {
      type: 'category',
      label: 'Queries',
      items: [{ type: 'autogenerated', dirName: 'queries' }],
    },
    {
      type: 'category',
      label: 'Summaries',
      items: [{ type: 'autogenerated', dirName: 'summaries' }],
    },
    {
      type: 'doc',
      id: 'log',
      label: 'Change Log',
    },
  ],
};
