const presentationsSidebar = require('./sidebars.presentations');

module.exports = {
  wikiSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'doc', id: 'concepts/README' },
      items: [
        { type: 'doc', id: 'concepts/README', label: 'Concepts Overview' },
        { type: 'doc', id: 'concepts/accessibility-in-bitcoin', label: 'Accessibility in Bitcoin' },
        { type: 'doc', id: 'concepts/ai-and-bitcoin', label: 'AI and Bitcoin' },
        { type: 'doc', id: 'concepts/bitcoin-address-types', label: 'Bitcoin Address Types' },
        { type: 'doc', id: 'concepts/bitcoin-education', label: 'Bitcoin Education' },
        { type: 'doc', id: 'concepts/bitcoin-inheritance-guide', label: 'Bitcoin Inheritance Guide' },
        { type: 'doc', id: 'concepts/bitcoin-key-holder-instructions', label: 'Bitcoin Key Holder Instructions' },
        { type: 'doc', id: 'concepts/bitcoin-node-types', label: 'Bitcoin Node Types' },
        { type: 'doc', id: 'concepts/bitcoin-protocol', label: 'Bitcoin Protocol' },
        { type: 'doc', id: 'concepts/chaumian-ecash', label: 'Chaumian Ecash' },
        { type: 'doc', id: 'concepts/circular-economy', label: 'Circular Economy' },
        { type: 'doc', id: 'concepts/custody-models', label: 'Custody Models' },
        { type: 'doc', id: 'concepts/home-mining', label: 'Home Mining' },
        { type: 'doc', id: 'concepts/lightning-network', label: 'Lightning Network' },
        { type: 'doc', id: 'concepts/mesh-networks', label: 'Mesh Networks' },
        { type: 'doc', id: 'concepts/mining-payout-schemas', label: 'Mining Payout Schemas' },
        { type: 'doc', id: 'concepts/multisig', label: 'Multisig' },
        { type: 'doc', id: 'concepts/no-kyc-acquisition', label: 'No-KYC Acquisition' },
        { type: 'doc', id: 'concepts/nostr', label: 'Nostr' },
        { type: 'doc', id: 'concepts/p2p-exchange', label: 'P2P Exchange' },
        { type: 'doc', id: 'concepts/payjoin', label: 'Payjoin' },
        { type: 'doc', id: 'concepts/privacy-stacks', label: 'Privacy Stacks' },
        { type: 'doc', id: 'concepts/proof-of-work', label: 'Proof of Work' },
        { type: 'doc', id: 'concepts/utxo-model', label: 'UTXO Model' },
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      link: { type: 'doc', id: 'comparisons/README' },
      items: [
        { type: 'doc', id: 'comparisons/README', label: 'Comparisons Overview' },
        { type: 'doc', id: 'comparisons/bitcoin-core-vs-knots', label: 'Bitcoin Core vs Knots' },
        { type: 'doc', id: 'comparisons/collaborative-custody-providers', label: 'Collaborative Custody Providers' },
        { type: 'doc', id: 'comparisons/mining-payout-schemas', label: 'Mining Payout Schemas' },
        { type: 'doc', id: 'comparisons/node-operating-systems', label: 'Node Operating Systems' },
        { type: 'doc', id: 'comparisons/privacy-stacks', label: 'Privacy Stacks' },
      ],
    },
    {
      type: 'category',
      label: 'Entities',
      link: { type: 'doc', id: 'entities/README' },
      items: [
        { type: 'doc', id: 'entities/README', label: 'Entities Overview' },
        { type: 'doc', id: 'entities/alby', label: 'Alby' },
        { type: 'doc', id: 'entities/azteco', label: 'Azteco' },
        { type: 'doc', id: 'entities/base58', label: 'Base58' },
        { type: 'doc', id: 'entities/bisq', label: 'Bisq' },
        { type: 'doc', id: 'entities/bitaxe', label: 'BitAxe' },
        { type: 'doc', id: 'entities/bitcoin-core', label: 'Bitcoin Core' },
        { type: 'doc', id: 'entities/bitcoin-knots', label: 'Bitcoin Knots' },
        { type: 'doc', id: 'entities/blockstream-green', label: 'Blockstream Green' },
        { type: 'doc', id: 'entities/braiins-hashpower', label: 'BRAIINS Hashpower' },
        { type: 'doc', id: 'entities/breez', label: 'Breez' },
        { type: 'doc', id: 'entities/caravan', label: 'CARAVAN' },
        { type: 'doc', id: 'entities/casa', label: 'CASA' },
        { type: 'doc', id: 'entities/cashu', label: 'Cashu' },
        { type: 'doc', id: 'entities/c-lightning', label: 'c-lightning' },
        { type: 'doc', id: 'entities/coldcard', label: 'Coldcard' },
        { type: 'doc', id: 'entities/datum', label: 'DATUM' },
        { type: 'doc', id: 'entities/electrum', label: 'Electrum' },
        { type: 'doc', id: 'entities/fold', label: 'Fold' },
        { type: 'doc', id: 'entities/hashguard', label: 'HashGuard' },
        { type: 'doc', id: 'entities/hashrate-autopilot', label: 'Hashrate Autopilot' },
        { type: 'doc', id: 'entities/hodlhodl', label: 'HodlHodl' },
        { type: 'doc', id: 'entities/hwi', label: 'HWI' },
        { type: 'doc', id: 'entities/joinmarket', label: 'JoinMarket' },
        { type: 'doc', id: 'entities/kaboom-racks', label: 'Kaboom Racks' },
        { type: 'doc', id: 'entities/ledger', label: 'Ledger' },
        { type: 'doc', id: 'entities/lnbits', label: 'LNbits' },
        { type: 'doc', id: 'entities/muun', label: 'Muun' },
        { type: 'doc', id: 'entities/mynode', label: 'MyNode' },
        { type: 'doc', id: 'entities/nunchuk', label: 'Nunchuk' },
        { type: 'doc', id: 'entities/ocean-xyz', label: 'Ocean.xyz' },
        { type: 'doc', id: 'entities/opennode', label: 'OpenNode' },
        { type: 'doc', id: 'entities/oshi-app', label: 'Oshi App' },
        { type: 'doc', id: 'entities/payjoin-dev-kit', label: 'Payjoin Dev Kit' },
        { type: 'doc', id: 'entities/phoenix', label: 'Phoenix' },
        { type: 'doc', id: 'entities/plebdevs', label: 'PlebDevs' },
        { type: 'doc', id: 'entities/pleblab', label: 'PlebLab' },
        { type: 'doc', id: 'entities/raspiblitz', label: 'RaspiBlitz' },
        { type: 'doc', id: 'entities/robosats', label: 'RoboSats' },
        { type: 'doc', id: 'entities/ronindojo', label: 'RoninDojo' },
        { type: 'doc', id: 'entities/samourai-wallet', label: 'Samourai Wallet' },
        { type: 'doc', id: 'entities/seedsigner', label: 'SeedSigner' },
        { type: 'doc', id: 'entities/simple-proof', label: 'Simple Proof' },
        { type: 'doc', id: 'entities/sparrow-wallet', label: 'Sparrow Wallet' },
        { type: 'doc', id: 'entities/specter-desktop', label: 'Specter Desktop' },
        { type: 'doc', id: 'entities/start-os', label: 'StartOS' },
        { type: 'doc', id: 'entities/stratum-v2', label: 'Stratum V2' },
        { type: 'doc', id: 'entities/strike', label: 'Strike' },
        { type: 'doc', id: 'entities/tapsigner', label: 'Tapsigner' },
        { type: 'doc', id: 'entities/trezor', label: 'Trezor' },
        { type: 'doc', id: 'entities/umbrel', label: 'Umbrel' },
        { type: 'doc', id: 'entities/unchained-capital', label: 'Unchained Capital' },
        { type: 'doc', id: 'entities/wasabi-wallet', label: 'Wasabi Wallet' },
        { type: 'doc', id: 'entities/whirlpool', label: 'Whirlpool' },
        { type: 'doc', id: 'entities/zeus', label: 'Zeus' },
      ],
    },
    ...presentationsSidebar,
    {
      type: 'category',
      label: 'Queries',
      link: { type: 'doc', id: 'queries/README' },
      items: [
        { type: 'doc', id: 'queries/README', label: 'Queries Overview' },
        { type: 'doc', id: 'queries/how-do-i-start-mining-at-home', label: 'How do I start mining at home?' },
        { type: 'doc', id: 'queries/what-privacy-stack-should-i-use-for-mobile', label: 'What privacy stack should I use for mobile?' },
        { type: 'doc', id: 'queries/which-custody-model-fits-my-threat-model', label: 'Which custody model fits my threat model?' },
      ],
    },
    {
      type: 'category',
      label: 'Summaries',
      link: { type: 'doc', id: 'summaries/README' },
      items: [
        { type: 'doc', id: 'summaries/README', label: 'Summaries Overview' },
        { type: 'doc', id: 'summaries/getonzero-synthesis', label: 'getonzero Synthesis' },
        { type: 'doc', id: 'summaries/mining-decentralization', label: 'Mining Decentralization' },
        { type: 'doc', id: 'summaries/privacy-as-a-spectrum', label: 'Privacy as a Spectrum' },
      ],
    },
    {
      type: 'doc',
      id: 'log',
      label: 'Change Log',
    },
  ],
};